export default [{
    id: 1,
    img:'./HomeImages/nisha.jpg',
    desc: 'Made with care and it is good for your skin',
    quantity: 6,
},
{
    id: 2,
    img:'./HomeImages/nisha.jpg',
    desc: 'Made with care and it is good for your skin',
    quantity: 10,
},
{
    id: 3,
    img:'./HomeImages/nisha2.jpg',
    desc: 'Made with care and it is good for your skin',
    quantity: 6,
},
{
    id: 4,
    img:'./HomeImages/nisha2.jpg',
    desc: 'Made with care and it is good for your skin',
    quantity: 12,
},
{
    id: 3,
    img:'./HomeImages/nisha2.jpg',
    desc: 'Made with care and it is good for your skin',
    quantity: 6,
},
{
    id: 3,
    img:'./HomeImages/nisha2.jpg',
    desc: 'Made with care and it is good for your skin',
    quantity: 6,
},
{
    id: 3,
    img:'./HomeImages/nisha2.jpg',
    desc: 'Made with care and it is good for your skin',
    quantity: 6,
},
{
    id: 3,
    img:'./HomeImages/nisha2.jpg',
    desc: 'Made with care and it is good for your skin',
    quantity: 6,
},
{
    id: 3,
    img:'./HomeImages/nisha2.jpg',
    desc: 'Made with care and it is good for your skin',
    quantity: 6,
},
{
    id: 3,
    img:'./HomeImages/nisha2.jpg',
    desc: 'Made with care and it is good for your skin',
    quantity: 6,
}]